### ISSUE TITLE
"Cannot invoke "app.controller.linAlg.Vector.getX()" because "B" is null" bug

### ISSUE THREAD

**Issue by MatthewFoster02** [S010MON/multi-agent-surveillance#293]
To recreate this bug move a human agent over where a sound source is emanating from. The simulation will freeze and you will get an error.

**Comment by S010MON** [comment]
It seems that this bug is only caused when the agent is perfectly on the sound source, given that an intersection is being found between the source and the agent, when they are on the same point, the vector A = B and the error occurs
![Screenshot from 2022-04-28 20-36-11](https://user-images.githubusercontent.com/10490509/165823296-e06d971e-2330-4167-9324-09aad50982ad.png)
