### ISSUE TITLE
Ray Intersection Low Count

### ISSUE THREAD

**Issue by trav-d13** [S010MON/multi-agent-surveillance#312]
Bug vision doesn't detect agents - branch 
Only showing 42 intersections out of 182, should be seeing all 182. 
Failing tests
`testNextBestMoveAfterFail()`
'testRankingSystem()`

**Comment by S010MON** [comment]
This bug is being caused (I think) by a change in the code that means that agents aren't just seen within their radius, they have a larger radius around them.  (see images)

`master` branch:
![Screenshot from 2022-05-15 12-37-48](https://user-images.githubusercontent.com/10490509/168468717-636cfc19-9864-4dd6-b5e9-a588063c2396.png)

`Bug vision doesn't detect agents` branch
![Screenshot from 2022-05-15 12-39-28](https://user-images.githubusercontent.com/10490509/168468736-8754ffb7-90a8-4bb1-be84-63cc6987ad32.png)


Notice that a large number of rays are registering as "hits" on the agents, despite not actually reaching them.  This is shown in the second image as a "Halo" around the red agent, and shown on the mini maps as agents being logged as small semi circles.  My hypothesis is that a change has been made to the agent-agent vision that is now causing the tests to fail due to one agent blocking out the other's view
