### ISSUE TITLE
Capture agent prevent slow-down

### ISSUE THREAD

**Issue by Jolijn2020** [S010MON/multi-agent-surveillance#354]
The beliefSet in CaptureAgent, which holds all the possible locations the seen intruder could be, doesn't have an upper limit rn.

When the intruder is captured, the beliefSet get exponentially large.
It keeps adding new possible locations to the beliefSet way faster than it's able to eliminate them.

This usually causes the App to crash.

(it was solved during experiments by reducing the max_tics_without_sight and by setting a limit on the max size of the beliefSet, after which nothing new gets added)

**Comment by S010MON** [comment]
![belief_set_temp_fix](https://user-images.githubusercontent.com/10490509/169705386-de6252c0-0a9d-4369-8bb9-a215484ebe3f.png)

**Comment by S010MON** [comment]
So, my reading of this situation is that the vector set becomes exponentially large because additional vectors keep getting added.  The `VectorSet` class wasn't designed for this task, so perhaps an implementation using a heap will be a better system?  We could make a heap that evaluates the "beliefs" by time since conception, or by distance to the agent.  We can also add an upper limit that removes any vectors over the maximum (like a one in, one out system) 

Perhaps a job for phase 3

**Comment by Jolijn2020** [comment]
I printed out the size of the beliefset to see how big it actually got and it become over 20000 or something before crashing, so there is probably something else wrong. There shouldn't be 20000 different distinct possible locations on the map when it's devided into squares of size maxWalk*maxWalk.
So probably a check to see if the vector already exists in the beliefSet would help.
![image](https://user-images.githubusercontent.com/72268363/169705817-0a457bbf-cf0a-40f8-af27-cfc6e3794854.png)

Although having a different way to store them might also help.

**Comment by S010MON** [comment]
The VectorSet should reduce to only individual occurrences, as It's built on the Java.util.Set class, so that is peculiar
