### ISSUE TITLE
Map equals method

### ISSUE THREAD

**Issue by Jolijn2020** [S010MON/multi-agent-surveillance#70]
Create a method in Map.java to compare maps

needed to test if maps that are created (and read in again) are the same as the original

**Comment by S010MON** [comment]
I think this could be left till later, for the moment let's assume that maps will be loaded using a FileChooser and will be saved manually by the user.

We can assume that only one instance of a Map is used at a time, if a new one is loaded, the old one is closed before the new one is accessed.  This means loading the same map causes no issues.

Comparing maps with agents that are moving will otherwise become a real headache

**Comment by S010MON** [comment]
Closed due to redundancy - only one map is used at a time
